import {
  Activity,
  AlertTriangle,
  ArrowDownToLine,
  ArrowUpRight,
  BarChart3,
  BrainCircuit,
  CalendarDays,
  CheckCircle2,
  CircleDollarSign,
  CircleHelp,
  CopyCheck,
  Download,
  Droplets,
  Eraser,
  FileSpreadsheet,
  FileText,
  HeartPulse,
  Landmark,
  LogOut,
  MapPin,
  Menu,
  Package,
  PieChart,
  ReceiptText,
  RefreshCcw,
  Repeat2,
  Search,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Tags,
  Target,
  TrendingDown,
  TrendingUp,
  UploadCloud,
  Utensils,
  Wallet,
  WalletCards,
  X,
  Zap
} from "lucide-react";

const ICONS = {
  activity: Activity,
  alert: AlertTriangle,
  bank: Landmark,
  brain: BrainCircuit,
  calendar: CalendarDays,
  chart: BarChart3,
  check: CheckCircle2,
  coins: CircleDollarSign,
  copy: CopyCheck,
  download: Download,
  file: FileText,
  health: HeartPulse,
  help: CircleHelp,
  income: ArrowDownToLine,
  inspect: Search,
  leak: Droplets,
  logout: LogOut,
  menu: Menu,
  package: Package,
  pending: Activity,
  pin: MapPin,
  pie: PieChart,
  receipt: ReceiptText,
  refund: RefreshCcw,
  repeat: Repeat2,
  report: FileSpreadsheet,
  savings: Wallet,
  search: Search,
  scale: Scale,
  shield: ShieldCheck,
  shopping: ShoppingBag,
  sparkles: Sparkles,
  spend: WalletCards,
  store: Store,
  tag: Tags,
  target: Target,
  "trend-down": TrendingDown,
  "trend-up": TrendingUp,
  transfer: ArrowUpRight,
  upload: UploadCloud,
  utensils: Utensils,
  wallet: Wallet,
  warning: AlertTriangle,
  waste: Eraser,
  zap: Zap,
  close: X
};

/** Render a consistent line icon without emoji fallbacks. */
export default function AppIcon({ name = "activity", size = 18, strokeWidth = 1.8, className = "", ...props }) {
  const Icon = ICONS[String(name || "activity").toLowerCase()] ?? Activity;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} {...props} />;
}
